/**
 * mockData.ts
 * 
 * This file contains all mock data for the teacher dashboard including
 * student assignments, assignments, and classes.
 */

import { Assignment, ClassInfo, StudentAssignment } from "./types";
import { generateRandomDate, generateRandomStatus, generateRandomTimeSpent, generateRandomWordCount } from "./mockDataGenerators";

// Mock data for student assignments
export const mockStudentAssignments: StudentAssignment[] = [
  {
    studentId: "1",
    assignmentId: "1",
    studentName: "Emma Johnson",
    status: "submitted",
    startTime: "2023-11-02T14:30:00Z",
    submissionTime: "2023-11-10T16:45:00Z",
    lastActive: "2023-11-10T16:45:00Z",
    timeSpent: 120,
    wordCount: 950,
    copyPasteCount: 3,
    citationCount: 5,
    content: "The evolution of American literature reflects the nation's history and cultural development. From the early colonial period to the modern era, American writers have explored themes of identity, freedom, individualism, and social justice...",
    comments: [
      {
        id: "c1",
        studentId: "1",
        assignmentId: "1",
        teacherId: "t1",
        teacherName: "Dr. Smith",
        text: "Excellent analysis of the historical context. Consider expanding on your comparison between Modernist and Postmodernist approaches.",
        timestamp: "2023-11-11T10:15:00Z",
        resolved: true
      }
    ]
  },
  {
    studentId: "2",
    assignmentId: "1",
    studentName: "James Wilson",
    status: "in_progress",
    startTime: "2023-11-05T09:20:00Z",
    submissionTime: null,
    lastActive: "2023-11-12T15:30:00Z",
    timeSpent: 85,
    wordCount: 620,
    copyPasteCount: 1,
    citationCount: 2,
    content: "American literature has undergone significant transformations throughout history. Beginning with the transcendentalists like Emerson and Thoreau, who emphasized individualism and nature, to the realists like Mark Twain who depicted everyday life...",
    comments: []
  },
  {
    studentId: "3",
    assignmentId: "1",
    studentName: "Michael Chen",
    status: "not_started",
    startTime: null,
    submissionTime: null,
    lastActive: null,
    timeSpent: 0,
    wordCount: 0,
    copyPasteCount: 0,
    citationCount: 0,
    content: null,
    comments: []
  },
  {
    studentId: "4",
    assignmentId: "1",
    studentName: "Sophia Patel",
    status: "in_progress",
    startTime: "2023-11-10T11:45:00Z",
    submissionTime: null,
    lastActive: "2023-11-10T12:15:00Z",
    timeSpent: 30,
    wordCount: 250,
    copyPasteCount: 0,
    citationCount: 1,
    content: "The development of American literature is closely tied to the country's historical events and social movements. This essay will explore how writers like Fitzgerald, Hemingway, and Faulkner captured the disillusionment of the post-WWI era...",
    comments: []
  },
  {
    studentId: "5",
    assignmentId: "2",
    studentName: "Emma Johnson",
    status: "in_progress",
    startTime: "2023-11-08T10:00:00Z",
    submissionTime: null,
    lastActive: "2023-11-12T09:15:00Z",
    timeSpent: 90,
    wordCount: 580,
    copyPasteCount: 0,
    citationCount: 3,
    content: "Newton's laws of motion form the foundation of classical mechanics. This problem set explores various applications of these laws in everyday scenarios...",
    comments: []
  },
  // Adding 10 more assignments for English Literature (Assignment ID 1)
  {
    studentId: "6",
    assignmentId: "1",
    studentName: "Oliver Martinez",
    status: "submitted",
    startTime: generateRandomDate(10),
    submissionTime: generateRandomDate(5),
    lastActive: generateRandomDate(5),
    timeSpent: generateRandomTimeSpent(70, 180),
    wordCount: generateRandomWordCount(700, 1200),
    copyPasteCount: Math.floor(Math.random() * 5),
    citationCount: Math.floor(Math.random() * 8),
    content: "American literature has been shaped by diverse cultural influences and historical events. From the early colonial writings to contemporary prose, there is a rich tapestry of voices that reflect America's complex identity...",
    comments: []
  },
  {
    studentId: "7",
    assignmentId: "1",
    studentName: "Isabella Kim",
    status: "in_progress",
    startTime: generateRandomDate(8),
    submissionTime: null,
    lastActive: generateRandomDate(2),
    timeSpent: generateRandomTimeSpent(40, 110),
    wordCount: generateRandomWordCount(300, 800),
    copyPasteCount: Math.floor(Math.random() * 3),
    citationCount: Math.floor(Math.random() * 4),
    content: "The journey of American literature from its colonial beginnings to its current diverse state mirrors the nation's own development. Writers such as Washington Irving, Nathaniel Hawthorne, and Edgar Allan Poe established a uniquely American voice...",
    comments: []
  },
  {
    studentId: "8",
    assignmentId: "1",
    studentName: "Ethan Williams",
    status: "submitted",
    startTime: generateRandomDate(12),
    submissionTime: generateRandomDate(7),
    lastActive: generateRandomDate(7),
    timeSpent: generateRandomTimeSpent(90, 160),
    wordCount: generateRandomWordCount(800, 1100),
    copyPasteCount: Math.floor(Math.random() * 2),
    citationCount: Math.floor(Math.random() * 6),
    content: "American literature emerged as a distinct literary tradition during the 19th century with writers like Walt Whitman and Emily Dickinson creating poetry that broke from European traditions both in form and content...",
    comments: []
  },
  {
    studentId: "9",
    assignmentId: "1",
    studentName: "Ava Rodriguez",
    status: generateRandomStatus(),
    startTime: generateRandomDate(9),
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(4) : null,
    lastActive: generateRandomDate(1),
    timeSpent: generateRandomTimeSpent(50, 140),
    wordCount: generateRandomWordCount(400, 900),
    copyPasteCount: Math.floor(Math.random() * 4),
    citationCount: Math.floor(Math.random() * 5),
    content: "The Harlem Renaissance marked a pivotal moment in American literary history, giving voice to Black writers and artists who explored themes of identity, racism, and cultural heritage...",
    comments: []
  },
  {
    studentId: "10",
    assignmentId: "1",
    studentName: "Noah Thompson",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(60, 150),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(500, 1000),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 7),
    content: generateRandomStatus() === "not_started" ? null : "The Beat Generation of the 1950s revolutionized American literature with works that challenged conventional values and literary forms. Writers like Jack Kerouac, Allen Ginsberg, and William S. Burroughs explored themes of spirituality, sexuality, and drug use...",
    comments: []
  },
  {
    studentId: "11",
    assignmentId: "1",
    studentName: "Sophia Lee",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(70, 180),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(600, 1100),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 4),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 6),
    content: generateRandomStatus() === "not_started" ? null : "Contemporary American literature reflects the diversity of American society, with voices from various cultural, ethnic, and social backgrounds contributing to a rich tapestry of literary expression...",
    comments: []
  },
  {
    studentId: "12",
    assignmentId: "1",
    studentName: "Jackson Brown",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(9) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(4) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(80, 160),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(700, 1000),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 5),
    content: generateRandomStatus() === "not_started" ? null : "American Gothic literature established a unique tradition with works characterized by darkness, mystery, and the supernatural. Edgar Allan Poe, Nathaniel Hawthorne, and later Stephen King exemplify this tradition...",
    comments: []
  },
  {
    studentId: "13",
    assignmentId: "1",
    studentName: "Mia Garcia",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(60, 150),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(500, 900),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 7),
    content: generateRandomStatus() === "not_started" ? null : "The American Dream has been a central theme in American literature, explored through various perspectives by writers such as F. Scott Fitzgerald, John Steinbeck, and Arthur Miller...",
    comments: []
  },
  {
    studentId: "14",
    assignmentId: "1",
    studentName: "Lucas Taylor",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(70, 170),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(600, 1100),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 4),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 6),
    content: generateRandomStatus() === "not_started" ? null : "Modernism in American literature reflected the rapid social and technological changes of the early 20th century. Writers like Ernest Hemingway, William Faulkner, and T.S. Eliot experimented with new literary techniques to capture the fragmentation and alienation of modern life...",
    comments: []
  },
  
  // Adding 8 more assignments for Physics Problem Set (Assignment ID 2)
  {
    studentId: "15",
    assignmentId: "2",
    studentName: "Charlotte Wilson",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(60, 150),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(400, 700),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 4),
    content: generateRandomStatus() === "not_started" ? null : "This problem set addresses the application of Newton's laws of motion to various scenarios including forces on inclined planes and friction calculations...",
    comments: []
  },
  {
    studentId: "16",
    assignmentId: "2",
    studentName: "Henry Davis",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(80, 160),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(500, 800),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 1),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    content: generateRandomStatus() === "not_started" ? null : "Energy conservation is a fundamental principle in physics. This problem set explores various scenarios where mechanical energy is conserved or transformed...",
    comments: []
  },
  {
    studentId: "17",
    assignmentId: "2",
    studentName: "Amelia Martinez",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(9) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(4) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(70, 140),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(450, 750),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 4),
    content: generateRandomStatus() === "not_started" ? null : "The concept of momentum is crucial in classical mechanics. This problem set examines various scenarios involving momentum conservation and collisions...",
    comments: []
  },
  {
    studentId: "18",
    assignmentId: "2",
    studentName: "Benjamin Anderson",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(90, 170),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(550, 850),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 5),
    content: generateRandomStatus() === "not_started" ? null : "Rotational dynamics is an extension of linear dynamics to rotating systems. This problem set explores the principles of torque, angular momentum, and rotational inertia...",
    comments: []
  },
  {
    studentId: "19",
    assignmentId: "2",
    studentName: "Harper Thomas",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(60, 130),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(400, 650),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 1),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    content: generateRandomStatus() === "not_started" ? null : "Fluid mechanics deals with the behavior of fluids at rest and in motion. This problem set examines concepts such as pressure, buoyancy, and fluid flow...",
    comments: []
  },
  {
    studentId: "20",
    assignmentId: "2",
    studentName: "Evelyn Clark",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(9) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(4) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(80, 150),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(500, 750),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    content: generateRandomStatus() === "not_started" ? null : "Thermodynamics is the study of heat, temperature, and their relation to energy and work. This problem set explores the laws of thermodynamics and their applications...",
    comments: []
  },
  {
    studentId: "21",
    assignmentId: "2",
    studentName: "Daniel Hill",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(70, 140),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(450, 700),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 1),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 4),
    content: generateRandomStatus() === "not_started" ? null : "Oscillatory motion is a type of periodic motion that repeats itself in a regular cycle. This problem set examines simple harmonic motion and its applications...",
    comments: []
  },
  {
    studentId: "22",
    assignmentId: "2",
    studentName: "Victoria Young",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(90, 160),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(550, 800),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    content: generateRandomStatus() === "not_started" ? null : "Wave motion is a disturbance that travels through a medium, transferring energy without transferring matter. This problem set explores mechanical waves, sound waves, and their properties...",
    comments: []
  },
  
  // Adding 13 more assignments for History Research Paper (Assignment ID 3)
  {
    studentId: "23",
    assignmentId: "3",
    studentName: "Joseph Walker",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(90, 180),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(800, 1400),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 8),
    content: generateRandomStatus() === "not_started" ? null : "The French Revolution (1789-1799) marked a pivotal moment in European history, leading to significant social and political changes that reshaped the continent and influenced global politics...",
    comments: []
  },
  {
    studentId: "24",
    assignmentId: "3",
    studentName: "Elizabeth Scott",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(100, 200),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(900, 1500),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 4),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 10),
    content: generateRandomStatus() === "not_started" ? null : "The Industrial Revolution transformed economic and social structures across Europe and North America, leading to urbanization, technological innovation, and new social classes...",
    comments: []
  },
  {
    studentId: "25",
    assignmentId: "3",
    studentName: "Gabriel Green",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(9) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(4) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(80, 170),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(700, 1300),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 7),
    content: generateRandomStatus() === "not_started" ? null : "The Civil Rights Movement in the United States (1954-1968) fought to end institutionalized racial discrimination, disenfranchisement, and racial segregation...",
    comments: []
  },
  {
    studentId: "26",
    assignmentId: "3",
    studentName: "Samantha Adams",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(110, 190),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(1000, 1600),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 5),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 12),
    content: generateRandomStatus() === "not_started" ? null : "World War I (1914-1918) was a global conflict that redrew national boundaries, collapsed empires, and set the stage for future conflicts with its unresolved tensions...",
    comments: []
  },
  {
    studentId: "27",
    assignmentId: "3",
    studentName: "David Turner",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(90, 180),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(800, 1400),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 3),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 9),
    content: generateRandomStatus() === "not_started" ? null : "The Cold War (1947-1991) was a period of geopolitical tension between the United States and the Soviet Union and their respective allies that shaped international relations for decades...",
    comments: []
  },
  {
    studentId: "28",
    assignmentId: "3",
    studentName: "Olivia Parker",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(9) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(4) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(100, 200),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(900, 1500),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 4),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 11),
    content: generateRandomStatus() === "not_started" ? null : "The Renaissance was a period of cultural, artistic, and intellectual revival that bridged the gap between the Middle Ages and modern history in Europe...",
    comments: []
  },
  {
    studentId: "29",
    assignmentId: "3",
    studentName: "William Baker",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(10) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(5) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(1) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(80, 170),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(700, 1300),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 2),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 8),
    content: generateRandomStatus() === "not_started" ? null : "The American Revolution (1775-1783) established the United States as an independent nation and set forth democratic principles that influenced political developments worldwide...",
    comments: []
  },
  {
    studentId: "30",
    assignmentId: "3",
    studentName: "Grace Nelson",
    status: generateRandomStatus(),
    startTime: generateRandomStatus() !== "not_started" ? generateRandomDate(11) : null,
    submissionTime: generateRandomStatus() === "submitted" ? generateRandomDate(6) : null,
    lastActive: generateRandomStatus() !== "not_started" ? generateRandomDate(2) : null,
    timeSpent: generateRandomStatus() === "not_started" ? 0 : generateRandomTimeSpent(110, 190),
    wordCount: generateRandomStatus() === "not_started" ? 0 : generateRandomWordCount(1000, 1600),
    copyPasteCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 5),
    citationCount: generateRandomStatus() === "not_started" ? 0 : Math.floor(Math.random() * 12),
    content: generateRandomStatus() === "not_started" ? null : "The Great Depression (1929-1939) was a severe worldwide economic downturn that had profound social and political implications, leading to significant policy reforms...",
    comments: []
  },
  {
    studentId: "31",
    assignmentId: "3",
    studentName: "Samuel Carter",
    status: generateRandomStatus(),
    startTime: generateRandomStatus()
