
/**
 * client.ts
 * 
 * This file sets up and exports the Supabase client for use throughout the application.
 * It provides access to authentication, database, storage, and other Supabase services.
 * 
 * Created by: Authentiya Development Team
 * Created on: 2023-12-01
 * 
 * Revision History:
 * - 2024-01-15: Added types import for better TypeScript support by Authentiya Team
 * - 2024-06-22: Updated with comprehensive documentation by Authentiya Team
 * 
 * Preconditions:
 * - Requires valid Supabase URL and API key to be defined
 * 
 * Input Types:
 * - None directly, uses environment variables
 * 
 * Postconditions:
 * - Creates and exports a configured Supabase client instance
 * 
 * Return:
 * - SupabaseClient<Database> - Configured Supabase client instance
 * 
 * Error Conditions:
 * - Will throw an error if Supabase URL or key is missing
 * 
 * Side Effects:
 * - Establishes connection to Supabase services
 * 
 * Invariants:
 * - Client will maintain the same configuration throughout the application lifecycle
 * 
 * Known Faults:
 * - None
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase connection parameters
const SUPABASE_URL = "https://ujxbqwnbxtivwkbkbotb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqeGJxd25ieHRpdndrYmtib3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTczNDIsImV4cCI6MjA1NzI5MzM0Mn0.JoVRkPTfqZrykD0kmPZnS2BtI8FUwEz4HCsQO2QKrBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Create and export the Supabase client instance
 * This client can be imported and used throughout the application
 * to interact with Supabase services (auth, database, storage, etc.)
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
